"""initial schema

Revision ID: 19cc31159d59
Revises:
Create Date: 2026-09-08 01:07:52.920767
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "19cc31159d59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("quantity_unit", sa.String(length=20), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("comparison_unit", sa.String(length=20), nullable=False),
        sa.Column("comparison_quantity", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_canonical_products_category", "canonical_products", ["category"], unique=False
    )
    op.create_index("ix_canonical_products_gtin", "canonical_products", ["gtin"], unique=False)
    op.create_table(
        "retailers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "scrape_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_slug", sa.String(length=50), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("products_seen", sa.Integer(), nullable=False),
        sa.Column("offers_written", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retailer_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("canonical_product_id", sa.Integer(), nullable=True),
        sa.Column("retailer_sku", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("brand_raw", sa.String(length=100), nullable=True),
        sa.Column("product_url", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("gtin", sa.String(length=20), nullable=True),
        sa.Column("size_text", sa.String(length=50), nullable=True),
        sa.Column("match_status", sa.String(length=20), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("match_candidates", sa.JSON(), nullable=False),
        sa.Column("scrape_source", sa.String(length=100), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_product_id"],
            ["canonical_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer_id", "retailer_sku", name="uq_retailer_product_sku"),
    )
    op.create_index(
        "ix_retailer_products_canonical",
        "retailer_products",
        ["canonical_product_id"],
        unique=False,
    )
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address_line1", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip_code", sa.String(length=10), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("served_zip_codes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer_id", "external_id", name="uq_store_retailer_external"),
    )
    op.create_index("ix_stores_zip_code", "stores", ["zip_code"], unique=False)
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_product_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("regular_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("loyalty_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("stock_status", sa.String(length=30), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unit_price_unit", sa.String(length=20), nullable=True),
        sa.Column("scrape_source", sa.String(length=100), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["retailer_product_id"],
            ["retailer_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer_product_id", "store_id", name="uq_offer_product_store"),
    )
    op.create_index("ix_offers_store", "offers", ["store_id"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_product_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("regular_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("loyalty_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("scrape_source", sa.String(length=100), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["retailer_product_id"],
            ["retailer_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_history_product_store",
        "price_history",
        ["retailer_product_id", "store_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_history_product_store", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index("ix_offers_store", table_name="offers")
    op.drop_table("offers")
    op.drop_index("ix_stores_zip_code", table_name="stores")
    op.drop_table("stores")
    op.drop_index("ix_retailer_products_canonical", table_name="retailer_products")
    op.drop_table("retailer_products")
    op.drop_table("scrape_runs")
    op.drop_table("retailers")
    op.drop_index("ix_canonical_products_gtin", table_name="canonical_products")
    op.drop_index("ix_canonical_products_category", table_name="canonical_products")
    op.drop_table("canonical_products")
    # ### end Alembic commands ###
