"""Deterministic category rules for the supported grocery staples.

Each category defines the unit prices are compared in, which query words map to it, and
keyword rules that decide whether a retailer title belongs to the category. Titles that
match an exclusion never enter the category, so "peanut butter" never competes with butter.
"""

import re
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Category:
    key: str
    label: str
    comparison_unit: str  # canonical unit from app.normalize.units.UNITS
    comparison_label: str  # human label, e.g. "egg", "lb"
    query_terms: tuple[str, ...]  # user queries that map here
    search_query: str  # what we send to retailers
    include: tuple[str, ...]  # regexes; at least one must match the title
    exclude: tuple[str, ...] = field(default_factory=tuple)  # regexes; none may match


CATEGORIES: dict[str, Category] = {
    c.key: c
    for c in [
        Category(
            key="eggs",
            label="Eggs",
            comparison_unit="count",
            comparison_label="egg",
            query_terms=("eggs", "egg", "dozen eggs"),
            search_query="eggs",
            include=(r"\beggs?\b",),
            exclude=(
                r"\bpan\b",
                r"cooker",
                r"poacher",
                r"timer",
                r"\bring\b",
                r"slicer",
                r"separator",
                r"mold",
                r"holder",
                r"\bcups?\b",
                r"\bdye\b",
                r"decorat",
                r"toy",
                r"egg\s*bites?",
                r"deviled",
                r"liquid",
                r"egg\s*whites?",
                r"noodle",
                r"salad",
                r"pickled",
                r"roll",
                r"sandwich",
                r"quiche",
                r"boiled",
                r"cooked",
                r"bake",
                r"scramble",
                r"omelet",
                r"substitute",
                r"nog",
                r"chocolate",
                r"candy",
                r"pasta",
                r"kimchi",
                r"muffin",
                r"biscuit",
                r"burrito",
                r"wrap",
                r"bowl",
                r"frittata",
                r"\bmix\b",
                r"replacer",
                r"vegan",
                r"plant",
            ),
        ),
        Category(
            key="milk",
            label="Milk",
            comparison_unit="gal",
            comparison_label="gal",
            query_terms=("milk", "whole milk", "2% milk", "dairy milk"),
            search_query="milk",
            include=(r"\bmilk\b",),
            exclude=(
                r"almond",
                r"\boat\b",
                r"\bsoy",
                r"cashew",
                r"coconut",
                r"walnut",
                r"macadamia",
                r"hazelnut",
                r"\bpea\b",
                r"rice milk",
                r"hemp",
                r"flax",
                r"pistachio",
                r"milked",
                r"creamer",
                r"buttermilk",
                r"powder",
                r"condensed",
                r"evaporated",
                r"kefir",
                r"yogurt",
                r"tea",
                r"shake",
                r"chocolate",
                r"strawberry",
                r"coffee",
                r"latte",
                r"cereal",
                r"cookie",
                r"candy",
                r"bar\b",
                r"ice cream",
                r"pudding",
                r"goat",
                r"sheep",
                r"formula",
                r"toddler",
                r"protein",
                r"eggnog",
                r"nog\b",
                r"heavy cream",
                r"sour cream",
                r"whipping cream",
                r"light cream",
                r"coffee cream",
                r"clotted",
                r"half\s*(?:and|&|n)\s*half",
                r"plant",
                r"non-dairy",
                r"nondairy",
                r"dairy-free",
                r"dairy free",
                r"barista",
                r"caramel",
                r"vanilla",
                r"banana",
                r"frozen",
            ),
        ),
        Category(
            key="chicken_breast",
            label="Chicken breast",
            comparison_unit="lb",
            comparison_label="lb",
            query_terms=("chicken breast", "chicken breasts", "chicken", "boneless chicken"),
            search_query="chicken breast",
            include=(r"chicken\s+breasts?",),
            exclude=(
                r"thai",
                r"coconut",
                r"sauce",
                r"glazed",
                r"sesame",
                r"orange",
                r"korean",
                r"mexican",
                r"southwest",
                r"caribbean",
                r"jerk",
                r"cajun",
                r"italian",
                r"greek",
                r"mediterranean",
                r"chipotle",
                r"sriracha",
                r"sweet",
                r"sous vide",
                r"entr[eé]e",
                r"meal",
                r"kit\b",
                r"skillet",
                r"bites?\b",
                r"chunks",
                r"pulled",
                r"shredded",
                r"kabob",
                r"kebab",
                r"crusted",
                r"marinated",
                r"stuffed",
                r"sausage",
                r"nugget",
                r"cooked",
                r"grilled",
                r"smoked",
                r"roasted",
                r"fried",
                r"salad",
                r"soup",
                r"strips?\b",
                r"tenderloin",
                r"tenders?\b",
                r"breaded",
                r"seasoned",
                r"skewer",
                r"sandwich",
                r"wrap",
                r"bowl",
                r"pizza",
                r"pasta",
                r"burrito",
                r"dumpling",
                r"jerky",
                r"deli",
                r"sliced",
                r"lunch",
                r"broth",
                r"stock",
                r"dog",
                r"cat\b",
                r"pet",
                r"treat",
                r"canned",
                r"can\b",
                r"frozen meal",
                r"dinner",
                r"entree",
                r"ready",
                r"rotisserie",
                r"diced",
                r"ground",
                r"patties",
                r"cutlets?\b",
                r"garlic",
                r"herb",
                r"bourbon",
                r"whiskey",
                r"rosemary",
                r"lemon",
                r"teriyaki",
                r"bbq",
                r"barbecue",
                r"buffalo",
                r"pesto",
                r"spice",
                r"\brub\b",
                r"pepper",
                r"parmesan",
                r"pecan",
                r"stuffing",
                r"fajita",
                r"taco",
                r"curry",
                r"honey",
            ),
        ),
        Category(
            key="rice",
            label="Rice",
            comparison_unit="lb",
            comparison_label="lb",
            query_terms=("rice", "white rice", "brown rice", "jasmine rice", "basmati rice"),
            search_query="rice",
            include=(r"\brice\b",),
            exclude=(
                r"cakes?\b",
                r"noodle",
                r"cracker",
                r"chips?\b",
                r"pudding",
                r"vinegar",
                r"\bmilk\b",
                r"flour",
                r"paper",
                r"cereal",
                r"krispies",
                r"crispies",
                r"fried",
                r"ready",
                r"cooked",
                r"microwav",
                r"bowl",
                r"pilaf",
                r"\bmix\b",
                r"seasoning",
                r"wild rice",
                r"syrup",
                r"bran",
                r"protein",
                r"rolls?\b",
                r"wrap",
                r"cup\b",
                r"cups\b",
                r"minute",
                r"instant",
                r"pouch",
                r"steamed",
                r"side",
                r"soup",
                r"salad",
                r"sushi roll",
                r"dog",
                r"cat\b",
                r"pet",
                r"drink",
                r"beverage",
                r"wine",
                r"sake",
                r"malt",
                r"cake",
                r"bar\b",
                r"bars\b",
                r"pasta",
                r"risotto",
                r"snack",
                r"crisp",
                r"puff",
                r"popped",
                r"stick",
                r"rice cooker",
                r"cookie",
            ),
        ),
        Category(
            key="bread",
            label="Bread",
            comparison_unit="oz",
            comparison_label="oz",
            query_terms=("bread", "sandwich bread", "loaf", "white bread", "wheat bread"),
            search_query="bread",
            include=(r"\bbread\b",),
            exclude=(
                r"crumb",
                r"pudding",
                r"banana",
                r"zucchini",
                r"pumpkin",
                r"\bmix\b",
                r"flour",
                r"sticks?\b",
                r"crisps?\b",
                r"chips?\b",
                r"\bdip\b",
                r"spread",
                r"tea bread",
                r"pound cake",
                r"cake",
                r"gingerbread",
                r"cornbread",
                r"shortbread",
                r"stuffing",
                r"machine",
                r"bowl",
                r"crouton",
                r"dough\b",
                r"dessert",
                r"sweet",
                r"cinnamon",
                r"raisin",
                r"monkey",
                r"garlic bread",
                r"cheese bread",
                r"frozen",
                r"knife",
                r"box",
                r"bag\b",
                r"bags\b",
                r"basket",
                r"crust",
                r"pizza",
                r"beer",
                r"soda",
                r"date",
                r"nut bread",
                r"pet",
                r"dog",
                r"cat\b",
                r"toast\b",
                r"toasts\b",
            ),
        ),
        Category(
            key="butter",
            label="Butter",
            comparison_unit="lb",
            comparison_label="lb",
            query_terms=("butter", "salted butter", "unsalted butter", "stick butter"),
            search_query="butter",
            include=(r"\bbutter\b",),
            exclude=(
                r"loaf",
                r"streusel",
                r"cinnamon",
                r"everything",
                r"chocolate",
                r"maple",
                r"biscoff",
                r"speculoos",
                r"sesame",
                r"macadamia",
                r"hemp",
                r"pastry",
                r"puff",
                r"croissant",
                r"rum\b",
                r"whipped",
                r"sprinkle",
                r"mix\b",
                r"dip\b",
                r"roll",
                r"peanut",
                r"almond",
                r"cashew",
                r"sunflower",
                r"seed",
                r"\bnut\b",
                r"nuts\b",
                r"cocoa",
                r"shea",
                r"body",
                r"apple",
                r"pumpkin",
                r"cookie",
                r"bean",
                r"lettuce",
                r"baby butter",
                r"buttermilk",
                r"butterfly",
                r"butternut",
                r"spread",
                r"ghee",
                r"popcorn",
                r"sauce",
                r"flavor",
                r"cracker",
                r"toffee",
                r"chicken",
                r"candy",
                r"cake",
                r"pecan",
                r"walnut",
                r"hazelnut",
                r"pistachio",
                r"coconut",
                r"mango",
                r"honey",
                r"garlic",
                r"herb",
                r"truffle",
                r"powder",
                r"oil\b",
                r"ranch",
                r"pretzel",
                r"chips?\b",
                r"bar\b",
                r"bars\b",
                r"waffle",
                r"biscuit",
                r"lotion",
                r"balm",
                r"lip",
                r"hand",
                r"ice cream",
                r"cream cheese",
                r"creamer",
                r"plant",
                r"vegan",
                r"dairy-free",
                r"dairy free",
                r"tahini",
                r"pie",
                r"soap",
                r"tart",
                r"crisp",
                r"cookies",
                r"scotch",
                r"brickle",
                r"corn\b",
                r"fish",
                r"shrimp",
                r"lobster",
                r"bagel",
                r"bread",
                r"muffin",
                r"squash",
                r"beans",
                r"cups?\b",
                r"pecans",
            ),
        ),
        Category(
            key="bananas",
            label="Bananas",
            comparison_unit="lb",
            comparison_label="lb",
            query_terms=("bananas", "banana", "organic bananas"),
            search_query="bananas",
            include=(
                r"^(?:organic\s+|fair\s*trade\s+|conventional\s+|fresh\s+)*"
                r"(?:baby\s+|mini\s+|red\s+|burro\s+|manzano\s+|yellow\s+)?"
                r"bananas?(?:\s*(?:bunch|each|,).*)?$",
            ),
            exclude=(
                r"bread",
                r"muffin",
                r"chips?\b",
                r"granola",
                r"yogurt",
                r"smoothie",
                r"cake",
                r"dried",
                r"pudding",
                r"plantain",
                r"holder",
                r"flavor",
                r"baby food",
                r"puree",
                r"frozen",
                r"pepper",
                r"juice",
                r"bar\b",
                r"bars\b",
                r"cereal",
                r"cookie",
                r"candy",
                r"protein",
                r"powder",
                r"milk",
                r"ice cream",
                r"drink",
                r"sorbet",
                r"nut\b",
                r"oat",
                r"pancake",
                r"waffle",
                r"popsicle",
                r"pops?\b",
                r"candle",
                r"incense",
                r"toy",
                r"leaf",
                r"leaves",
                r"doughnut",
                r"donut",
                r"pie",
                r"strawberry",
                r"cream\b",
                r"crunch",
                r"blossom",
                r"foster",
                r"split",
                r"tea\b",
                r"squash",
                r"pouch",
                r"squeeze",
                r"snack",
                r"crisps",
                r"pancakes",
                r"bites?\b",
            ),
        ),
    ]
}

_QUERY_INDEX: dict[str, str] = {
    term: category.key for category in CATEGORIES.values() for term in category.query_terms
}


def normalize_query(query: str) -> str:
    return re.sub(r"\s+", " ", query.strip().lower())


def category_for_query(query: str) -> Category | None:
    """Map a user query (e.g. "Eggs", "chicken breast") to a supported category."""
    q = normalize_query(query)
    key = _QUERY_INDEX.get(q)
    if key is None and q.endswith("s"):
        key = _QUERY_INDEX.get(q[:-1])
    if key is None:
        key = _QUERY_INDEX.get(q + "s")
    return CATEGORIES[key] if key else None


def title_matches_category(title: str, category: Category) -> bool:
    """True when a retailer title satisfies the category's include and exclude rules."""
    text = title.lower()
    if not any(re.search(pattern, text) for pattern in category.include):
        return False
    return not any(re.search(pattern, text) for pattern in category.exclude)
